version: "3.9"

services:
  php:
    build:
      context: '.'
      dockerfile: ./docker/php/.Dockerfile
    volumes:
      - ./:/app
    networks:
      - app-tier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '8000:8000'
      - '44300:44300'
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/app
      - ./docker/nginx/practice.conf:/opt/bitnami/nginx/conf/server_blocks/localhost.conf
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - app-tier
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dev_practice'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
